Q1 = "SELECT COUNT(id) FROM Movie WHERE year < 2000;"
Q2 = "SELECT AVG(rank) FROM Movie WHERE year = 1991;"
Q3 = "SELECT MIN(rank) FROM Movie WHERE year = 1991;"
Q4 = "SELECT fname, lname FROM Actor INNER JOIN Cast on id == pid WHERE mid = 27;"
Q5 = "SELECT COUNT(mid) FROM Actor INNER JOIN Cast on id == pid WHERE fname = 'Jon' AND lname = 'Dough';"
Q6 = "SELECT name FROM Movie WHERE name LIKE 'Young Latin Girls%' AND (year BETWEEN 2003 AND 2006);"
Q7 = "SELECT DISTINCT fname,lname FROM Director INNER JOIN MovieDirector on Director.id == did INNER JOIN Movie on Movie.id == mid WHERE name LIKE 'Star Trek%';"
Q8 = "SELECT name FROM Movie INNER JOIN Cast on `Movie`.`id` == `Cast`.`mid` INNER JOIN Actor on `Actor`.`id` == `Cast`.`pid` INNER JOIN MovieDirector on `MovieDirector`.`mid` == `Cast`.`mid` INNER JOIN Director on `Director`.`id`= `MovieDirector`.`did` WHERE (Director.fname = 'Jackie (I)' AND Director.lname = 'Chan') AND (Actor.fname = 'Jackie (I)' AND Actor.lname='Chan') ORDER BY name ASC;"
Q9 = "SELECT fname, lname FROM Director INNER JOIN MovieDirector on Director.id == did INNER JOIN Movie on Movie.id == mid WHERE year = 2001 GROUP By did HAVING COUNT(mid) >= 4 ORDER BY fname ASC,lname DESC;"
Q10 = "SELECT gender, count(id) FROM Actor GROUP BY gender HAVING gender = 'M' OR gender = 'F' ORDER BY gender ASC;"
Q11 = "SELECT DISTINCT M1.name, M2.name, M1.rank, M1.year FROM Movie AS M1 CROSS JOIN Movie AS M2 on M1.name != M2.name AND M1.year== M2.year AND M1.rank == M2.rank ORDER BY M1.name ASC LIMIT 100;"
Q12 = "SELECT fname, year, AVG(rank) As rank FROM Cast INNER JOIN Movie on `Cast`.`mid` == `Movie`.`id` INNER JOIN Actor on `Cast`.`pid` = `Actor`.`id` GROUP BY `Actor`.`id`, year ORDER BY fname ASC,year DESC LIMIT 100;"
Q13 = "SELECT Actor.fname, Director.fname, Avg(rank) AS score FROM Movie INNER JOIN Cast on `Movie`.`id` == `Cast`.`mid` INNER JOIN Actor on `Actor`.`id` == `Cast`.`pid` INNER JOIN MovieDirector on `MovieDirector`.`mid` == `Cast`.`mid` INNER JOIN Director on `Director`.`id`= `MovieDirector`.`did` GROUP BY `ACTOR`.`id`,`Director`.`id` HAVING COUNT(`Movie`.`id`) >= 5 ORDER BY score DESC, Director.fname ASC, Actor.fname DESC LIMIT 100;"